### ISSUE TITLE
cam detour has a nil value

### ISSUE THREAD

**Issue by Hazeofdream** [Vurv78/Safety#17]
![image](https://github.com/Vurv78/Safety/assets/74027566/f0f26bf3-3fbc-4736-b24c-9227a82332c5)

**Comment by Hazeofdream** [comment]
what

**Comment by Vurv78** [comment]
Probably a server or another plugin issue, I can just delete the cam detour now though since rubat finally patched the cam.End* crash, and it warns you itself.
